apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: nexusml
spec:
  selector:
    app: backend
  ports:
  - name: api
    protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
